name = "rearjackman"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "rearjackman.com", custom_domain = true }
]

[triggers]
crons = [
  "*/20 * * * THU",
  "*/20 * * * FRI",
  "*/20 * * * SAT",
  "*/20 * * * SUN",
  "*/20 * * * MON",
]

[[kv_namespaces]]
binding = "CACHE"
id = "a3426f35669c4e048a0d28416200bf4c"
preview_id = "f6158a5648344a6281f99c087fa8e050"

[[d1_databases]]
binding = "DB"
database_name = "rearjackman"
database_id = "c90c6cfb-13b0-42fd-9a52-8210a211ad22"
migrations_dir = "migrations"

[observability]
[observability.logs]
enabled = true
invocation_logs = true


[[queues.producers]]
queue = "rearjackman-sync"
binding = "SYNC_QUEUE"

[[queues.consumers]]
queue = "rearjackman-sync"
max_batch_size = 1
max_batch_timeout = 5

